### ISSUE TITLE
[CHORE] 자동 배포 적용

### ISSUE THREAD

**Issue by leeeeeyeon** [umc-bonheur/bonheur-server#128]
## 📝 todo
- [x] Github Actions 스크립트 파일 작성
- [x] appspec.yml, deploy.sh 파일 작성
- [x] yml 파일 변경
