### ISSUE TITLE
[Fix] 통계 api - 응답 값 변경

### ISSUE THREAD

**Issue by youngeun-dev** [umc-bonheur/bonheur-server#214]
## todo

피그마에 명시 되어있는 값으로 수정해야 합니다.
 
<img width="793" alt="스크린샷 2023-01-18 오전 1 13 15" src="https://user-images.githubusercontent.com/78026977/218941186-54a50fea-1b51-4f3b-89cc-ee8b67076639.png">

- [ ] 시간별 api (ex. dawn -> 새벽)
- [ ] 월별 api (ex. apr -> 04)
- [ ] 요일별 api (ex. wed -> 수)
