### ISSUE TITLE
[Fix] 행복 기록 작성 및 수정 기능 로직 수정

### ISSUE THREAD

**Issue by dana-developer** [umc-bonheur/bonheur-server#80]
## 📝 todo
- [x] DTO 클래스 수정 : CreateBoardRequest, CreateBoardResponse
- [x] Tag 관련 DTO 클래스 생성 : CreateTagRequest, CreateTagResponse
- [x] Service 로직 수정
- [x] controller 로직 수정
